# Generated by Django 4.2 on 2023-04-27 05:00
from django.db.migrations import RunPython
from django.db import migrations


def func(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'newspaper_db.json')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [RunPython(func, reverse_func)]
